apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deploymnet
spec:
  serviceName: "postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "ruby"
            - name: POSTGRES_USER
              value: "ruby"
            - name: POSTGRES_PASSWORD
              value: "mypass"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        emptyDir: {}
